# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/
services:
  dashapp:
    build:
      context: .
    volumes:
      - ../gsf_dash_settings_private:/usr/src/gsf_dash_settings_private
      - type: bind
        source: ./db
        target: /usr/src/app/db
    ports:
      - 8051:8051
    command: bash container_wrapper.sh

  # dataloader:
  #   build:
  #     context: .
  #   volumes:
  #     # bind volume to 
  #     - ../gsf_dash_settings_private:/usr/src/gsf_dash_settings_private
  #     - type: bind
  #       source: ./db
  #       target: /usr/src/app/db
  #   command: python3 src/dataloader -d 2024-02-02


